# data generated by Xijia Liu
set.seed(2021)
n = 50 # init: n = 50
N = 30 # init: N = 30
p = 0.6
p_a = 0.4
p_b = 0.7
z = rbinom (n, 1, p)
x = rbinom (n, N, p_a)
x1 = rbinom (n, N, p_b)
x [z != 1] = x1[z != 1]
rm(z , x1)

prob = function(x, theta, N) {
    return(theta^x * (1 - theta)^(N - x))
}

e_step = function(x, theta, p, N) {
    lik_a = prob(x, theta[1], N)
    lik_b = prob(x, theta[2], N)
    p_a = (p * lik_a) / (p * lik_a + (1-p) * lik_b)
    p_b = 1 - p_a
    p = mean(p_a)
    return(c(p_a %*% x, p_a %*% (N - x), p_b %*% x, p_b %*% (N - x), p))
}

m_step = function(e) {
    theta_a = e[1] / (e[1] + e[2])
    theta_b = e[3] / (e[3] + e[4])
    p = e[5]
    return(c(theta_a, theta_b, p))
}  

em = function(trials, theta, p, N, iter=5) {
    for (i in 1:iter) {
        print(paste("Iter:", i))
        print(
            paste(
                "(theta_a, theta_b, pi):",
                round(theta[1], 3),
                round(theta[2], 3), 
                round(p, 3),
                sep=" "
            )
        )
        out = m_step(e_step(trials, theta, p, N))
        theta = out[1:2]
        p = out[3]
    }
    return(out)
}

# EM-algorithm results!
theta_a = runif(1)
theta_b = runif(1)
p = runif(1)
res = em(x, c(theta_a, theta_b), p, N, iter=10)
